Fix stuff

diff --git a/bin/electron_deploy b/bin/electron_deploy
--- a/bin/electron_deploy
+++ b/bin/electron_deploy
@@ -1,11 +1,10 @@
 #!/bin/zsh
 
-
 pushd $HOME/sherman
 
 export SHERMAN_DIR=$HOME/sherman
 export SHERMAN_ENV="$(cat $HOME/sherman/CURRENT_ENV)"
 
-ssh electron -t "cd sherman && bin/deploy" || echo "something failed"
+ssh electron -t "cd sherman && bash bin/deploy" || echo "something failed"
 
 popd
