Use absolute volume path

diff --git a/bin/electron_deploy b/bin/electron_deploy
--- a/bin/electron_deploy
+++ b/bin/electron_deploy
@@ -6,6 +6,6 @@ pushd $HOME/sherman
 export SHERMAN_DIR=$HOME/sherman
 export SHERMAN_ENV="$(cat $HOME/sherman/CURRENT_ENV)"
 
-ssh electron -t "cd sherman && bin/deploy";
+ssh electron -t "cd sherman && bin/deploy" || echo "something failed"
 
 popd
